### ISSUE TITLE
Error when trash radarr is used

### ISSUE THREAD

**Issue by tpdcl** [rcdailey/trash-updater#55] opened 2022-04-25 14:42 UTC
```[INF] Processing Quality Definition: Movie
[INF] Number of updated qualities: 0
[ERR] An exception occurred during git operations on path: REDACTED
LibGit2Sharp.NotFoundException: No valid git object identified by 'master' exists in the repository.
   at LibGit2Sharp.Core.Ensure.GitObjectIsNotNull(GitObject gitObject, String identifier) in /_/LibGit2Sharp/Core/Ensure.cs:line 265
   at LibGit2Sharp.Repository.RevParse(String revision, Reference& reference, GitObject& obj) in /_/LibGit2Sharp/Repository.cs:line 1750
   at LibGit2Sharp.Commands.Checkout(IRepository repository, String committishOrBranchSpec, CheckoutOptions options) in /_/LibGit2Sharp/Commands/Checkout.cs:line 47
   at VersionControl.GitRepository.ForceCheckout(String branch) in D:\a\trash-updater\trash-updater\src\VersionControl\GitRepository.cs:line 26
   at TrashLib.Radarr.CustomFormat.Guide.LocalRepoCustomFormatJsonParser.CheckoutAndUpdateRepo() in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\Guide\LocalRepoCustomFormatJsonParser.cs:line 69
[INF] Deleting local git repo and retrying git operation...
[ERR] An exception occurred during git operations on path: REDACTED
LibGit2Sharp.LibGit2SharpException: could not load ssl libraries
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in /_/LibGit2Sharp/Core/Proxy.cs:line 275
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in /_/LibGit2Sharp/Repository.cs:line 793
   at VersionControl.Wrappers.LibGit2SharpRepositoryStaticWrapper.Clone(String sourceUrl, String workdirPath, CloneOptions options) in D:\a\trash-updater\trash-updater\src\VersionControl\Wrappers\LibGit2SharpRepositoryStaticWrapper.cs:line 8
   at VersionControl.GitRepositoryFactory.DeleteAndCloneRepo(String repoUrl, String repoPath, String branch) in D:\a\trash-updater\trash-updater\src\VersionControl\GitRepositoryFactory.cs:line 42
   at VersionControl.GitRepositoryFactory.CreateAndCloneIfNeeded(String repoUrl, String repoPath, String branch) in D:\a\trash-updater\trash-updater\src\VersionControl\GitRepositoryFactory.cs:line 27
   at TrashLib.Radarr.CustomFormat.Guide.LocalRepoCustomFormatJsonParser.CheckoutAndUpdateRepo() in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\Guide\LocalRepoCustomFormatJsonParser.cs:line 68
[ERR] Unrecoverable Exception
LibGit2Sharp.LibGit2SharpException: could not load ssl libraries
   at TrashLib.Radarr.CustomFormat.Guide.LocalRepoCustomFormatJsonParser.GetCustomFormatJson() in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\Guide\LocalRepoCustomFormatJsonParser.cs:line 49
   at TrashLib.Radarr.CustomFormat.Processors.GuideProcessor.BuildGuideDataAsync(IReadOnlyCollection`1 config, CustomFormatCache cache) in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\Processors\GuideProcessor.cs:line 58
   at TrashLib.Radarr.CustomFormat.CustomFormatUpdater.Process(Boolean isPreview, RadarrConfiguration config) in D:\a\trash-updater\trash-updater\src\TrashLib\Radarr\CustomFormat\CustomFormatUpdater.cs:line 33
   at Trash.Command.RadarrCommand.Process() in D:\a\trash-updater\trash-updater\src\Trash\Command\RadarrCommand.cs:line 56
   at Trash.Command.ServiceCommand.ExecuteAsync(IConsole console) in D:\a\trash-updater\trash-updater\src\Trash\Command\ServiceCommand.cs:line 53
Exiting due to previous exception 
```

**Comment by tpdcl** [comment] 2022-04-25 14:43
Config file:
```
# A starter config to use with Trash Updater. Most values are set to "reasonable defaults".
# Update the values below as needed for your instance. You will be required to update the
# API Key and URL for each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://github.com/rcdailey/trash-updater/wiki/Configuration-Reference

# Configuration specific to Sonarr
sonarr:
    # Set the URL/API Key to your actual instance
  - base_url: REDACTED
    api_key: REDACTED

    # Quality definitions from the guide to sync to Sonarr. Choice: anime, series, hybrid
    quality_definition: series

    # Release profiles from the guide to sync to Sonarr. Types: anime, series
    # You can optionally add tags and make negative scores strictly ignored
    release_profiles:
      - type: series

# Configuration specific to Radarr.
radarr:
  # Set the URL/API Key to your actual instance
  - base_url: REDACTED
    api_key: REDACTED

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
    # the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: true

    custom_formats:
      # A list of custom formats to sync to Radarr. Must match the "name" in the importable JSON.
      # Do NOT use the heading names here, those do not work! These are case-insensitive.
      - names:
          - BR-DISK
          - EVO (no WEBDL)
          - LQ
          - x265 (720/1080p)
          - 3D

        # Uncomment the below properties to specify one or more quality profiles that should be
        # updated with scores from the guide for each custom format. Without this, custom formats
        # are synced to Radarr but no scores are set in any quality profiles.

        quality_profiles:
          - name: 1080p
          - name: 4K
#          - name: Quality Profile 2
#            #score: -9999 # Optional score to assign to all CFs. Overrides scores in the guide.
#            #reset_unmatched_scores: true # Optionally set other scores to 0 if they are not listed in 'names' above.
```

**Comment by rcdailey** [comment] 2022-04-25 16:44
Are you using Ubuntu v22?

**Comment by rcdailey** [comment] 2022-04-25 16:52
Marking as duplicate of #54 to keep conversation in one place.

**Closed by rcdailey** 2022-04-25 16:52 UTC

**Comment by tpdcl** [comment] 2022-04-26 07:23
Hey, sorry for the late answer! No, I'm on Fedora Server 36.

**Comment by rcdailey** [comment] 2022-04-26 14:54
No problem. Please see the linked issue for the solution. I'd like to keep conversation there.
